### ISSUE TITLE
Generating 2 "createIndex()" commands with same names instead one. 

### ISSUE THREAD

**Issue by Matvik** [tmukherjee13/yii2-reverse-migration#1]
Generating 2 "createIndex()" commands with the same names instead one, when we have one index with 2 collums in table.

**Comment by odannyc** [comment]
I had the same issue.

It needs to send in 1 `createIndex` with an array of names as the third parameter.

I can issue a PR.

**Comment by tmukherjee13** [comment]
If you can issue a PR that's highly appreciated. Else I'll give it a look this weekend.
Currently not changing it as I am changing the migration files to use DB abstraction layer provided by Yii.

**Comment by tmukherjee13** [comment]
Multi-column index issues are fixed in [d99162c](https://github.com/tmukherjee13/yii2-reverse-migration/commit/d99162c2cd03eb5cac753a780684c095c468bc46).
