### ISSUE TITLE
add Unique index to migration

### ISSUE THREAD

**Issue by des1roer** [tmukherjee13/yii2-reverse-migration#12]
table DDL

        CREATE TABLE `unit_transport` (
		  `id` INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
		  `unit_id` INTEGER(10) UNSIGNED NOT NULL,
		  `transport_id` INTEGER(10) UNSIGNED NOT NULL,
		  PRIMARY KEY USING BTREE (`id`),
		  UNIQUE KEY `id` USING BTREE (`id`),
		  UNIQUE KEY `unit_transport_idx1` USING BTREE (`unit_id`, `transport_id`),
		  KEY `unit_id` USING BTREE (`unit_id`),
		  KEY `transport_id` USING BTREE (`transport_id`),
		  CONSTRAINT `unit_transport_fk1` FOREIGN KEY (`unit_id`) REFERENCES `unit` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
		  CONSTRAINT `unit_transport_fk2` FOREIGN KEY (`transport_id`) REFERENCES `transport` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
		) ENGINE=InnoDB
		AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
		;

migration

          <?php

		use yii\db\Migration;

		/**
		 * Handles the creation for table `{{%unit_transport}}`.
		 */
		class m171119_070028_create_table_unit_transport extends Migration
		{
		    /**
		     * @inheritdoc
		     */
		    public function safeUp()
		    {
		        $this->createTable('{{%unit_transport}}', [

		            'id' => $this->primaryKey()->unsigned()->notNull(),
		            'unit_id' => $this->integer(10)->unsigned()->notNull(),
		            'transport_id' => $this->integer(10)->unsigned()->notNull(),

		        ]);
		 
		        // creates index for column `unit_id`
		        $this->createIndex(
		            'unit_transport_fk1',
		            '{{%unit_transport}}',
		            'unit_id'
		        );

		        // add foreign key for table `unit`
		        $this->addForeignKey(
		            'unit_transport_fk1',
		            '{{%unit_transport}}',
		            'unit_id',
		            '{{%unit}}',
		            'id',
		            'CASCADE'
		        );

		        // creates index for column `transport_id`
		        $this->createIndex(
		            'unit_transport_fk2',
		            '{{%unit_transport}}',
		            'transport_id'
		        );

		        // add foreign key for table `transport`
		        $this->addForeignKey(
		            'unit_transport_fk2',
		            '{{%unit_transport}}',
		            'transport_id',
		            '{{%transport}}',
		            'id',
		            'CASCADE'
		        );

		        $this->createIndex('idx_unique_unit_id_transport_id',
		            '{{%unit_transport}}',
		            ['unit_id', 'transport_id'],
		            true);
		    }

		    /**
		     * @inheritdoc
		     */
		    public function safeDown()
		    {
		        // drops foreign key for table `unit`
		        $this->dropForeignKey(
		            'unit_transport_fk1',
		            '{{%unit_transport}}'
		        );

		        // drops index for column `unit_id`
		        $this->dropIndex(
		            'unit_transport_fk1',
		            '{{%unit_transport}}'
		        );

		        // drops foreign key for table `transport`
		        $this->dropForeignKey(
		            'unit_transport_fk2',
		            '{{%unit_transport}}'
		        );

		        // drops index for column `transport_id`
		        $this->dropIndex(
		            'unit_transport_fk2',
		            '{{%unit_transport}}'
		        );

		        $this->dropIndex(
		            'idx_unique_unit_id_transport_id',
		            '{{%unit_transport}}'
		        );

		        $this->dropTable('{{%unit_transport}}');
		    }
		}

**Comment by tmukherjee13** [comment]
can you explain the issue @des1roer

**Comment by des1roer** [comment]
add unique index form DB in generated migration please

**Comment by tmukherjee13** [comment]
@des1roer  the unique index is there and should be generating if your DB has it.

**Comment by des1roer** [comment]
are not generated, mysql 5.7

**Comment by des1roer** [comment]
please ad unique indexes to migartion

**Comment by tmukherjee13** [comment]
based on your pasted code, i can see the unique index is created for  'unit_id' and 'transport_id'.

Closing this issue as it is not valid.
