### ISSUE TITLE
Non-static method Formatter::getColType() should not be called statically

### ISSUE THREAD

**Issue by andkas** [tmukherjee13/yii2-reverse-migration#6]
> php yii migration/table table_name

have error:

> PHP Deprecated Warning 'yii\base\ErrorException' with message 'Non-static method tmukherjee13\migration\console\components\Formatter::getColType() should not be called statically, assuming $this from incompatible context'

same problem with Formatter::formatCol()

php 5.5
yii 2.0.6

**Comment by andkas** [comment]
same problem with Formatter::formatCol()

**Comment by tmukherjee13** [comment]
@andkas can you please specify the usage scenario and your specification, because i am unable to reproduce the error.
